### ISSUE TITLE
Feature 1 View Champs

### ISSUE THREAD

**Issue by paulpark330** [paulpark330/ajax-project#1]
## 📐 Functionality

User can view a list of champions

Scroll or swipe to see more

## 🖼️ Wireframes

![Group 40](https://user-images.githubusercontent.com/85209433/127197317-99660cba-c064-41b4-94a0-9bb9cce37624.png)

## ✅ Task List

- [x] HTML and CSS layout
- [x] Pull data from API using XMLhttprequest
- [x] Every champion should be a clickable element
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
