### ISSUE TITLE
Feature 2 Search Champs

### ISSUE THREAD

**Issue by paulpark330** [paulpark330/ajax-project#2]
## 📐 Functionality

User can use the search bar to look for a champion
Not case-sensitive
Ex) If use types "tr", result should show Aatrox, Tristana, Trundle, Tryndamere

## 🖼️ Wireframes

![Group 42](https://user-images.githubusercontent.com/85209433/127198260-6dcc89fb-52ef-4568-b26f-60fb1f85efe9.png)

## ✅ Task List

- [x] Create input element for search bar
- [x] Style search bar with CSS
- [x] Query the DOM to select all champions
- [x] Make a function to show the champions that include the champs in the search bar and hide all other champs
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
