### ISSUE TITLE
Feature 3 Add to List

### ISSUE THREAD

**Issue by paulpark330** [paulpark330/ajax-project#3]
## 📐 Functionality

User can add champions to comparison lists
User will be able to switch between home and comparison view
Add button will only show when hovered

## 🖼️ Wireframes

![Group 47](https://user-images.githubusercontent.com/85209433/127199889-0a0ae380-f7c7-4d4e-ac9d-46df267347eb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add plus icon to each champion
- [x] Only display plus icon when champion is hovered
- [x] Create comparison view
- [x] Click event will add champion to comparison view

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
