### ISSUE TITLE
Feature 4 Remove from List

### ISSUE THREAD

**Issue by paulpark330** [paulpark330/ajax-project#4]
## 📐 Functionality

User can remove champions from comparison list
Remove button will only show when hovered

## 🖼️ Wireframes

![Group 50](https://user-images.githubusercontent.com/85209433/127200346-8ff45129-246c-48bc-af5e-e462320af3d3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Remove icon should be visible when cursor is hovered
- [x] Click event on the remove icon should remove the champion from DOM tree
- [x] User shouldn't have to refresh to see that the champion was removed
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
