### ISSUE TITLE
Feature 5 Compare by Level

### ISSUE THREAD

**Issue by paulpark330** [paulpark330/ajax-project#5]
## 📐 Functionality

User can compare champion's base stats by each level

## 🖼️ Wireframes

![Group 51 (1)](https://user-images.githubusercontent.com/85209433/127200808-62cecbfe-3d73-4ab7-99a9-45df2021dd8b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Make a mock DOM tree in the html for the select tag and the option tag
- [ ] Create a DOM tree in JS for each champion
- [ ] Edit the addChampion function to render the dropdown list along with the pictures
- [ ] Create a function to modify the base stats data depending on the selected dropdown list
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
